BlogTitle: Carlo Hamalainen
BlogDescription: Carlo Hamalainen
WelcomeHomepage: Carlo Hamalainen
NoEntries: nada
CommentsHeading: Comments
NoComments: No comments
CommentName: Name
CommentEmail: email (not published)
CommentUrl: URL (optional)
CommentText: Comment
AddCommentHeading: Add your comment
AddCommentButton: Submit
PleaseCorrectComment: Please correct your comment.
CommentAdded: Your comment has been added to the moderation queue.
